services:
  - type: web
    name: zerodha-backend
    env: node
    plan: free
    installCommand: npm install
    buildCommand: npm run build
    startCommand: npm start
    branch: main
    envVars:
      - key: PORT
        value: 3002
      - key: MONGO_URL
        value: 'mongodb+srv://soumyaranjanmahanna5_db_user:5l6NjvDzcPAPG58I@zerodhaclonecluster.y0pgluk.mongodb.net/zerodha?appName=ZerodhaCloneCluster'
